<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8xN9foX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8xN9foX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8xN9foX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8xN9foX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8xN9foX\App_KernelDevDebugContainer([
    'container.build_hash' => '8xN9foX',
    'container.build_id' => '056eadae',
    'container.build_time' => 1714029949,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8xN9foX');
