<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIAkmCdI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIAkmCdI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIAkmCdI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIAkmCdI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIAkmCdI\App_KernelDevDebugContainer([
    'container.build_hash' => 'IAkmCdI',
    'container.build_id' => '28575bbe',
    'container.build_time' => 1714032833,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIAkmCdI');
